name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create config.js
        run: |
          echo "const API_KEY_AUTH = '${{ secrets.API_KEY_AUTH }}';" > ./config.js

      - name: Verify config.js was created
        run: cat ./config.js

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./